### ISSUE TITLE
Update the script which creates demo users

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bz-database#1]
We need to update this script to use variables and the logic in the script 'user_creates_a_new_unit.sql'.

This is a more robust way to create groups and grant the relevant permission to the initial product creator.

**Comment by kaihendry** [comment]
Related to https://github.com/unee-t/bugzilla-customisation/issues/27

**Comment by franck-boullier** [comment]
Done! See [here](https://github.com/unee-t/bz-database/commit/9e0aef074d96000bca1ae171ea5a509861d9b658) for more details.
