### ISSUE TITLE
unit_create_new.sql failed: error=Error 1062: Duplicate entry '32767' for key 'PRIMARY'

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#100]
Looks like we have hit the smallint limit on Units in the dev environment.

**Comment by franck-boullier** [comment]
This is a NON trivial fix ---> BZ periodically the DB schema to what it think should be each time the .checksetup.pl script is triggered.

There is a good chance that the changes in the DB schema will be overridden at some unpredictable time in the future if we do not make sure that we understand how to make the .checksetup.pl script behave the way we want it to do (i.e keep the core BZ schema changes that we need to make).

Until this is taken care of we should delete some of the existing units in the DEV environment to make room for the automated Uilicious tests.

There is a [script to remove a unit and all the objects associated to this unit](https://github.com/unee-t/bz-database/blob/master/scripts/cleanup_remove_a_unit_bzfe.sql).
Input needed is the BZ unit ID and it will take care of the BZ side of things.

**Comment by franck-boullier** [comment]
@nbiton can you use the [script to remove a unit and all the objects associated to this unit](https://github.com/unee-t/bz-database/blob/master/scripts/cleanup_remove_a_unit_bzfe.sql) and cleanup some of the existing units in Unee-T so we have a spare 100 units that we could create as part of normal tests?

**Comment by nbiton** [comment]
@franck-boullier you suggest I do it one at a time to clean 100 units?

**Comment by dylanwh** [comment]
So we're going to make the flagtype id bigger in 
https://github.com/bugzilla/bugzilla/pull/75.

**Comment by franck-boullier** [comment]
Awesome! @dylanwh 
thanks

**Comment by kaihendry** [comment]
Merged @dylanwh's work in https://github.com/bugzilla/bugzilla/pull/75 and tested in {dev,demo}. We should not see this issue again. 🤞
