### ISSUE TITLE
demo db contributor@example.com password is undocumented

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#101]
Not sure what it is or how to reset it.

**Comment by franck-boullier** [comment]
can you give me more information on the context please? What are you trying to do? Which environment? What was supposed to happen? What's actually happening?

**Comment by kaihendry** [comment]
_Without_ downloading the dev database, I have been testing with [./db snapshots/unee-t_BZDb_clean_current.sql](https://github.com/unee-t/bz-database/blob/master/db%20snapshots/unee-t_BZDb_clean_current.sql) and it creates **contributor@example.com** by default. What's the password?

**Comment by franck-boullier** [comment]
This seems to be a part of a record in the table `audit_log`

The exact line is
> (1,'Bugzilla::User',1,'__create__',NULL,'contributor@example.com','2017-11-25 00:28:48'),

I don't think it actually creates an actual user, this looks like a residue from a very distant past that wasn't properly scrubbed out
---> there should be no user contributor@example.com created by by this script default AFAICT

**Comment by franck-boullier** [comment]
BZ users that are created by the script are
insert  into `profiles`(`userid`,`login_name`,`cryptpassword`,`realname`,`disabledtext`,`disable_mail`,`mybugslink`,`extern_id`,`is_enabled`,`last_seen_date`) values 
(1,'administrator@example.com','B8AgzURt,NDrX2Bt8stpgXPKsNRYaHmm0V2K1+qhfnt76oLAvN+Q{SHA-256}','Administrator','',0,1,NULL,1,'2018-02-02 00:00:00'),
(2,'temporary.agent@example.com','8IF0bErt,DWxzG95hJ7+7YGjCvCdMO+8IcCWdAW2+ojoSKnYxQYg{SHA-256}','Generic Agent','',0,1,NULL,1,NULL),
(3,'temporary.landlord@example.com','YxnRDOJe,h1YQJqMCsMi4JItnllV5tMNJSKNXpARxD/wkyyIuhQM{SHA-256}','Generic Landlord','',0,1,NULL,1,NULL),
(4,'temporary.tenant@example.com','lm6aQER6,H2pgJVfTP38j+7RE2rlPcekO5k1MYzMtvYRgOTQQw/M{SHA-256}','Generic Tenant','',0,1,NULL,1,NULL),
(5,'temporary.contractor@example.com','4ri3AF6X,Hlu9YmDzumnQdn5fr4J6kKbjDe/3KxJPPhCcwkYBqe4{SHA-256}','Generic Contractor','',0,1,NULL,1,NULL),
(6,'temporary.mgt.cny@example.com','dHGU8lRe,odrIC0TGEuEsYBAxm918zU2HWjsDHeEmMaT7mIQ5C/s{SHA-256}','Generic Management Company','',0,1,NULL,1,NULL);

https://github.com/unee-t/bz-database/blob/9acd53d3b149bc7981965c3ad9359cdc03180b60/db%20snapshots/unee-t_BZDb_clean_current.sql#L2180

**Comment by kaihendry** [comment]
There should be no @example addresses anymore. The pattern should be followed is documented in https://github.com/unee-t/bz-database/issues/111
