### ISSUE TITLE
We need a BZ vanilla reference

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bz-database#105]
@kaihendry in order to make sure that we have a good understanding of the BZFE DB schema specificity vs a vanilla Bugzilla install we need to have a reference point for comparaison purposes.

Can you help me spin a BZ vanilla install in a dedicated environment so I can do this analysis?
This is needed so we can fix #100 and be confident that we won't mess things up.

This will also be useful if we want to share some of the DB improvements we have made with the BZ community (ex: the index we created in some of the group map tables to improve login speed when there is a lot of groups to check against) 

Thanks

**Comment by kaihendry** [comment]
I plan to test https://github.com/bugzilla/bugzilla/pull/75 in the dev environment over the weekend.

As for spinning up an environment for your own testing, spinning up a local Docker environment would be easiest for me to recommend you: https://github.com/unee-t/bugzilla-customisation/blob/master/docker-compose.yml

Here you will have your own self contained mariadb and bugzilla.

Though you need to perhaps read up about Docker and of course having a working install as a prerequisite.

**Comment by kaihendry** [comment]
I'm viewing this as support a local setup. We do this, but issues like https://github.com/unee-t/bz-database/issues/111 make it tricky.

**Comment by kaihendry** [comment]
I sent the instructions over at https://unee-t.slack.com/archives/C7GL8EHFG/p1549874654000300
