### ISSUE TITLE
New user is able to see a pre-existing unit

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#107]
https://media.dev.unee-t.com/2019-02-03/new-user-Unit-exists.mp4

I'm not sure which repo is responsible for the bug, but I guess it's most likely to do with the default schema I just restored with: https://github.com/unee-t/bz-database/blob/master/db%20snapshots/unee-t_BZDb_clean_current.sql

**Comment by franck-boullier** [comment]
this is actually a feature: I have created a demo units in the DB so that every user can play with it right after the environment is spun out.

We can delete it if needed...

**Comment by franck-boullier** [comment]
If you want to delete that demo unit you can run the [script to remove a unit in the BZFE](https://github.com/unee-t/bz-database/blob/master/scripts/cleanup_remove_a_unit_bzfe.sql) and set the variable for the product_id to 1,

**Comment by franck-boullier** [comment]
BTW we also need to make sure that this demo unit is also deleted from the MEFE (if needed)

**Comment by kaihendry** [comment]
The troublesome unit was deleted, so I hopefully we won't see this again.
