### ISSUE TITLE
Unable able to handle Emoji

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#110]
<img width="1680" alt="screenshot 2019-02-05 at 8 46 07 am" src="https://user-images.githubusercontent.com/765871/52246889-8b0ca780-2922-11e9-9dfb-e5ecf94e5ff2.png">

`Error: failed [400] Error 1366: Incorrect string value: '\xF0\x9F\x90\xA2' for column 'unit_description_details' at row 1`

This could be a https://github.com/unee-t/bz-database schema issue.

**Comment by kaihendry** [comment]
Dylan over at Bugzilla knows how to fix this problem, so I suggest we solicit his services when we need to support Unicode.

**Comment by franck-boullier** [comment]
> Dylan over at Bugzilla knows how to fix this problem, so I suggest we solicit his services when we need to support Unicode.

Totally agree with that!
One idea is to convert all the tables and fields to Character Set `utf8` and Collation `utf8_unicode_ci`. This moves us further away from a BZ vanilla schema but this might be the right move. I'd love to have Dylan's perspective on that.
@kaihendry feel free to rope him in as you wish!

**Comment by dylanwh** [comment]
Hmm, by default the tables should be `utf8` in bugzilla 5. However `utf8` in mysql is a bit of a lie.
In BMO I introduced a new value for the 'utf8' parameter: utf8=utf8mb4. It would be good if I were to port that feature to bugzilla 5. Below is a summary about utf8/utf8mb4, mysql, and the parts of the conversion.

The MySQL `utf8` type only stores unicode characters that can be represented as 3 bytes or less. Emoji (and some other, possibly more important things) take 4 bytes.

The "real" utf8 type is `utf8mb4` but until about 2015 it wasn't practical to use. The reason for this is with 'utf8mb4' MySQL's storage format didn't have enough space. So `VARCHAR(255)` becomes `VARCHAR(192)` which is clearly not ideal.

So here's all the things that have to be aligned to support full utf8 in a mysql (before version 8) database.

# Settings 
- the `innodb_file_format` has to be set to Barracuda (this is the newer of the two current innodb formats)
- `innodb_file_per_table` has to be on (I believe this is the default for a long time)
- `innodb_large_prefix` has to be on.

# Schema

## Table Formats

Now that you're using Barracuda and you have large prefixes turned on, you alter the `ROW_FORMAT` of each table. The `ROW_FORMAT` should be either `Compressed` or `Dynamic`. The former is usually faster unless you have a *lot* of writes. We use `Compressed` for almost all tables.
[row format conversion part of BMO's code](https://github.com/mozilla-bteam/bmo/blob/89750e8205e6c178e83786cded14e89e58640bab/Bugzilla/DB/Mysql.pm#L345-L358)

## Character sets

Now if all the tables have the correct row format, you can use the `utf8mb4` character set. 
As for collation, `utf8mb4_unicode_520_ci` is a good bet because it's been supported for a few years.

**Comment by dylanwh** [comment]
More details about what we went through are in this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=bmo-emoji

**Comment by franck-boullier** [comment]
Thanks @dylanwh great insights!

We'll definitely work on migrating to utf8mb4 then.

Do you have any recommendation on the collation? I tend to go with `..._unicode_ci` but I noticed that BZ is using `..._general_ci`.
I was wondering what you would consider best as of today?

**Comment by franck-boullier** [comment]
@dylanwh 

# Request for clarification on the upgrade method:

I looked at your code here https://github.com/mozilla-bteam/bmo/blob/89750e8205e6c178e83786cded14e89e58640bab/Bugzilla/DB/Mysql.pm#L846-L852

If I understand correctly the approach you suggest is to:
1- Make sure that the pre-requisite are met in the Db (we should run MySQL 5.7+, InnoDb/Barracuda)
2- Alter the file Bugzilla/DB/Mysql.pm
3- Run the checksetup.pl script to apply these changes to the database.

Am I missing something?

# Alternative approach:

- Make sure that the pre-requisite are met in the Db (we should run MySQL 5.7+, InnoDb/Barracuda)
- Switch to InnoDb/Barracuda/Dynamic Rows: Run  the following SQL commands
``ALTER TABLE `table_name` ROW_FORMAT=DYNAMIC;``
- Convert to 'true' utf8 and the latest version of the unicode_ci collation 
``ALTER TABLE `table_name` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode520_ci;``

My Idea is to use SQL to generate SQL like this:
``
SELECT CONCAT("ALTER TABLE `"
	, TABLE_SCHEMA
	, '`.`'
	, TABLE_NAME
	,"` ROW_FORMAT=DYNAMIC;") AS `the_sql_to_run`
 FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_SCHEMA="my_bugzilla_database"
 AND TABLE_TYPE="BASE TABLE";
``

To make sure I get all the tables I need are considered during the conversion.

Do you See any reason not to do it this way @dylanwh?

**Comment by dylanwh** [comment]
> @dylanwh
> # Request for clarification on the upgrade method:
> 
> I looked at your code here https://github.com/mozilla-bteam/bmo/blob/89750e8205e6c178e83786cded14e89e58640bab/Bugzilla/DB/Mysql.pm#L846-L852
> 
> If I understand correctly the approach you suggest is to:
> 1- Make sure that the pre-requisite are met in the Db (we should run MySQL 5.7+, InnoDb/Barracuda)
> 2- Alter the file Bugzilla/DB/Mysql.pm
> 3- Run the checksetup.pl script to apply these changes to the database.
> 
> Am I missing something?

No, that's mostly correct. It is also controlled by a configuration directive so just because the code is updated doesn't force the SQL migration.

> Do you See any reason not to do it this way @dylanwh?

Yes, you Bugzilla/DB/Schema.pm is responsible for the database schema. Making changes to the schema without updating that is a brittle solution.

**Comment by dylanwh** [comment]
> Thanks @dylanwh great insights!
> 
> We'll definitely work on migrating to utf8mb4 then.
> 
> Do you have any recommendation on the collation? I tend to go with `..._unicode_ci` but I noticed that BZ is using `..._general_ci`.
> I was wondering what you would consider best as of today?
We use `utf8mb4_unicode_520_ci` which seems to work well enough in an international context.

**Comment by dylanwh** [comment]
Ok, so one thing I think I didn't understand here is that you're not *currently* using utf8? 
Bugzilla has supported unicode on mysql for a long time, but only characters inside the Basic Multilingual Plane. This is generally good enough for a lot of things. But reading into this it sounded like maybe you're using the old non-utf8 encoding.

This is a configuration issue, you can change the `utf8` param on the admin page, and re-run checksetup (which will take a while, but not as long as going to utf8mb4),

Documentation for this: https://bugzilla.readthedocs.io/en/5.0/administering/parameters.html#general

**Comment by dylanwh** [comment]
Ok, ignore the previous comment

**Comment by franck-boullier** [comment]
Pb should be fixed now thanks to PR #112 

We need to see what would be the most efficient way to make sure that our DB schema changes are not overriden if/when BZ is upgraded

**Comment by kaihendry** [comment]
There was about 5 recent [Invalid Request Content. Could not parse request body into json: Invalid UTF-8 start byte](https://media.dev.unee-t.com/2019-03-04/invalid-utf8-start-byte.mp4) errors. So I'm not confident Unicode is working.

Perhaps the issue is somewhere else now... perhaps Bugzilla is mangling the encoding. But bear in mind, it's the *same error* message as before in #73. Another possibility of course, is this error actually has nothing to do with supporting Unicode. I don't know.

**Comment by kaihendry** [comment]
We are getting quite a few [5xx errors in prod](https://media.dev.unee-t.com/2019-03-05/5xx.txt). I created this output via https://github.com/unee-t/5xx btw/

Ideally we could record the POST request for better debugging. Is that possible @nbiton ?

**Comment by kaihendry** [comment]
I just did a bold experiment by putting 😒 into a case comment. It actually works in dev and prod, except for a weird frontend rendering glitch that @nbiton should probably look at: https://media.dev.unee-t.com/2019-03-06/dev.mp4


So now I am thinking **DBD::mysql::db do failed: Lambda API returned error: Invalid Request Content.** means that I think we have JSON injection issue.

As @dylanwh points out if there [those variables contain a double quote, you're in trouble](https://github.com/unee-t/bz-database/blob/schema_v4.32.0_lambda_improvements/db%20scripts%20to%20add%20objects%20to%20the%20schema/Add_all_lambda_related_objects_v4.31.sql#L77-L90).

**Comment by franck-boullier** [comment]
Schema v4.32 is a fix for that.

**Comment by kaihendry** [comment]
I've added some further tests https://github.com/unee-t/rdslint/commit/3b278b462e90d7868c565511d8048d12e56fd2e3

<img src="https://s.natalian.org/2019-04-01/1554098734_2560x1440.png">

The following settings:

* character_set_database - latin1
* character_set_server - latin1
* collation_database - latin1_swedish_ci
* collation_server - latin1_swedish_ci

Appear incorrect in reference to https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by kaihendry** [comment]
I created a test "rest_api_example" database in the dev environment, and I could get Unicode working:
<img src="https://s.natalian.org/2019-04-02/1554184350_2560x1440.png">

So I assume the settings on the Bugzilla database need to be updated @franck-boullier since the RDS host seems configured correctly.

**Comment by franck-boullier** [comment]
Not sure what needs to be changed TBH: all the tables we are using in the BZ PROD are currently `utf8mb4_unicode_520_ci`

![image](https://user-images.githubusercontent.com/31331637/55381364-8e549600-5555-11e9-9ca7-522d7f36c621.png)

**Comment by kaihendry** [comment]
There is more to it:

```
[hendry@t480s db]$ ./connect.sh
Connecting to DEV auroradb.dev.unee-t.com
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
Variable_name   Value
character_set_client    utf8mb4
character_set_connection        utf8mb4
character_set_database  latin1
character_set_filesystem        utf8mb4
character_set_results   utf8mb4
character_set_server    utf8mb4
character_set_system    utf8
collation_connection    utf8mb4_unicode_ci
collation_database      latin1_swedish_ci
collation_server        utf8mb4_unicode_ci
mysql> [hendry@t480s db]$ ./connect.sh -p
PRODUCTION
Connecting to PROD auroradb.unee-t.com
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
Variable_name   Value
character_set_client    utf8mb4
character_set_connection        utf8mb4
character_set_database  utf8
character_set_filesystem        binary
character_set_results   utf8mb4
character_set_server    latin1
character_set_system    utf8
collation_connection    utf8mb4_general_ci
collation_database      utf8_general_ci
collation_server        latin1_swedish_ci
mysql> [hendry@t480s db]$
```
Btw IIUC it should be utf8mb4_unicode_ci and not utf8mb4_unicode_520_ci, but they could be the same for all I know.

**Comment by franck-boullier** [comment]
> it should be utf8mb4_unicode_ci and not utf8mb4_unicode_520_ci, but they could be the same for all I know.

`utf8mb4_unicode_520_ci` is the latest version and the version @dylanwh recommended we use ---> probably best to stick to that one.

**Comment by kaihendry** [comment]
When I run `SHOW CREATE PROCEDURE unit_create_with_dummy_users\G;` in dev, the tail end is:
```
character_set_client: utf8
collation_connection: utf8_general_ci
  Database Collation: utf8mb4_unicode_ci
ERROR:
No query specified

mysql> SHOW VARIABLES LIKE 'collation%';
Variable_name   Value
collation_connection    utf8mb4_general_ci
collation_database      utf8mb4_unicode_ci
collation_server        utf8mb4_unicode_ci
mysql> call unit_create_with_dummy_users;
ERROR 1048 (23000): Column 'name' cannot be null
mysql> SET @mefe_unit_id = 'foobar';
mysql> call unit_create_with_dummy_users;
ERROR 1267 (HY000): Illegal mix of collations (utf8mb4_unicode_520_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
mysql> SHOW SESSION VARIABLES LIKE 'collation_connection';
Variable_name   Value
collation_connection    utf8mb4_general_ci
```

*utf8mb4_unicode_520_ci* is causing me headaches. I am not sure what the way out is here. I don't know how to make my CLI connect as *utf8mb4_unicode_520_ci* and it appears _very uncommon_ when I've googled this requirement.

**Comment by kaihendry** [comment]
Are we aiming for utf8mb4 and utf8mb4_unicode_520_ci WRT `SELECT @@character_set_database,@@collation_database;`? @dylanwh

**Comment by kaihendry** [comment]
https://www.percona.com/live/e17/sites/default/files/slides/Collations%20in%20MySQL%208.0.pdf

I'm puzzled about:
* character_set_server latin1
* character_set_system utf8
* collation_connection utf8mb4_general_ci
* collation_server latin1_swedish_ci

https://s.natalian.org/2019-04-29/collation.txt

**Comment by kaihendry** [comment]
Just noticed bugzilla sending down SET NAMES utf8 https://s.natalian.org/2019-05-13/1557728282_2560x1440.png instead of utf8mb4. Am I missing a setting for bugzilla @dylanwh ?

**Comment by kaihendry** [comment]
Defer to https://github.com/unee-t/frontend/issues/850

Synthesis is running in all our environments and passes the simple Unicode test.
