### ISSUE TITLE
Document restore from scratch process

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#111]
We need to be mindful that test and demo user emails need to follow the test+xxxx@{dev,demo}.unee-t.com pattern.

* administrator password needs to be correctly setup to whatever is in the parameter store for BZFE_ADMIN_USER & BZFE_ADMIN_PASS
* unee_t_root user setup with privs
* BUGZILLA_ADMIN_KEY needs to setup as below:

```
echo "select count(*) from user_api_keys" | mysql -h auroradb.dev.unee-t.com -P 3306 -u root --password=$MYSQL_ROOT_PASSWORD bugzilla
mysql -h auroradb.dev.unee-t.com -P 3306 -u root --password=$MYSQL_ROOT_PASSWORD bugzilla << EOF
INSERT INTO user_api_keys (user_id, api_key) VALUES (1, "$(aws --profile uneet-dev ssm get-parameters --names BUGZILLA_ADMIN_KEY --with-decryption --query Parameters[0].Value --output text)");
EOF
```

**Comment by kaihendry** [comment]
Furthermore as @franck-boullier mention dev requires certain API and profiles to be set in advance.

**Comment by kaihendry** [comment]
Depending on whether {dev,demo} is restored, the account numbers for the `mysql.lambda_async` must be correctly defined!

<img src="https://s.natalian.org/2019-02-11/1549852473_2560x1440.png">

**Comment by franck-boullier** [comment]
We also need to make sure that the users are restored in the MEFE/Mongo environment too if we want to test the MEFE environment too

**Comment by kaihendry** [comment]
To create the hash for Bugzilla profiles, I'm told it's `perl -MBugzilla -MBugzilla::Util=bz_crypt -E 'say bz_crypt($ARGV[0])' password-plaintext`

**Comment by kaihendry** [comment]
We don't restore from scratch. 

For dev you could use https://media.dev.unee-t.com/2019-02-20/dev-1550629586.zip

The restore scripts are in:
* https://github.com/unee-t/frontend/tree/master/backup
* https://github.com/unee-t/bugzilla-customisation/tree/master/backup
