### ISSUE TITLE
Invitation mechanism on dev does not grant users the ability to create cases

### ISSUE THREAD

**Issue by nbiton** [unee-t/bz-database#117]
Re: https://unee-t.slack.com/archives/C6UM93HD2/p1551663295009800

After inviting a user to a unit (or a user "self-invites" when a new unit is created), the user can't create new cases on that unit, and the BZ API for case creation fails (the MEFE response is to point to case "undefined").
This is likely to stem from the invitation script not properly assigning the right permissions to the user for this unit, as has been witnessed before.

**Comment by franck-boullier** [comment]
I'm just seeing this.
Will look into that ASAP

**Comment by nbiton** [comment]
Just fixed by @franck-boullier by updating the DB procedures on dev to the correct updated version
