### ISSUE TITLE
Check for empty procedures

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bz-database#124]
The source of https://github.com/unee-t/lambda2sns/issues/9#issuecomment-478439130 was that the procedure `unit_create_with_dummy_users` had been corrupted in the DEV/STaging envo (it was empty).

We need to understand how and why it happened to make sure that we can avoid this in the future.

**Comment by kaihendry** [comment]
https://github.com/unee-t/rdslint's /checks checks for empty procedures. I recommend you run this check manually from Postman atm.

<img src="https://s.natalian.org/2019-04-09/1554775679_2560x1440.png">
