### ISSUE TITLE
Make db lambda compatible - Migrate to AWS Aurora

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bz-database#30]
In order to automate certain things and make sure that we have timely notification, we need to make sure the DB engine we use is compatible with AWS Lambda.

In order to do that we need to migrate our DB engine from MariaDB to AWS Aurora.

**Comment by kaihendry** [comment]
* [auroradb.dev.unee-t.com is already](https://github.com/unee-t/bugzilla-customisation/blob/master/aws-env.dev) running AuroraDB
* [auroradb.unee-t.com TODO](https://github.com/unee-t/bugzilla-customisation/blob/master/aws-env.prod) -> auroradb.unee-t.com
* [db.demo.unee-t.com is already running Auroradb](https://github.com/unee-t/bugzilla-customisation/blob/master/aws-env.demo), but without auroradb prefix. TODO auroradb.demo.unee-t.com CNAME end point bugzilla.c2waklyujftr.ap-southeast-1.rds.amazonaws.com

**Comment by kaihendry** [comment]
@franck-boullier https://ap-southeast-1.console.aws.amazon.com/rds/home?region=ap-southeast-1#dbinstance:id=abugzilla is up and running in the production (1924-5899-3663) account.

I also setup a read replica (abugzilla-ap-southeast-1a) which I think is good practice for production workloads. It can speed up things and offer some resiliency IIUC. **MYSQL_ROOT_PASSWORD** is the same and in the parameter store. Hopefully you can use you tool to sync from bugzilla-prod to abugzilla?

I haven't tweaked any settings yet. To mind I need to enable slow query log. Also get lambda permissions sorted & deploy [https://github.com/unee-t/lambda2sns](https://github.com/unee-t/lambda2sns) in the production account.

**Comment by kaihendry** [comment]
I'd like to keep this open until we are able to call lambda test is in place.
