### ISSUE TITLE
Publish events to lambda from the Aurora DB

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#36]
There is a [test lambda function](https://github.com/unee-t/lambda2sns) in the staging environment [arn:aws:lambda:ap-southeast-1:812644853088:function:alambda_simple](https://github.com/unee-t/bugzilla/issues/9#issuecomment-382581896). I expect message payloads to be sent there in the interim to achieve all our notification objectives, of yet which need to be defined.

Over time when the objectives are better defined, the lambda name etc will be updated.

**Comment by franck-boullier** [comment]
The first event that we will put there are notification each time a case is created, updated or a comment is added to a case.

**Comment by kaihendry** [comment]
After production RDS has been rebooted, Lambda: **alambda_simple** pushes the messsage to SNS: **atest** 

Subscribe to **atest** SNS to test and show payloads sent by database triggers that need to be written. 

Please refer to https://github.com/unee-t/lambda2sns/blob/master/tests/call-lambda-as-root.sh which exercises this feature across {dev,demo,prod} environments.

I suggest closing this bug and creating a new issue for each event you plan to implement. E.g. When a case is created et al.

**Comment by franck-boullier** [comment]
@kaihendry 
> I suggest closing this bug and creating a new issue for each event you plan to implement. E.g. When a case is created et al.

I'm fine with that (and well done!!)
