### ISSUE TITLE
Migration script to invite a user to multiple units at once

### ISSUE THREAD

**Issue by nbiton** [unee-t/bz-database#65]
This script would be run directly on a MongoDB instance / cluster by running it in CLI:
`mongo [connection params] [filename]`

The BZ user id and a list of BZ unit ids will be set as parameters in the start of the file.
After the script has finished generating all the invitations into Mongo, the "invite" lambda will need to be triggered manually to process all these pending invitations.

**Comment by franck-boullier** [comment]
This has been implemented and works
