### ISSUE TITLE
Default API key for demo.sql

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#72]
Following on from https://github.com/unee-t/bugzilla-customisation/issues/9#issuecomment-397164355

So I don't have to go through the painful process of setting up **BUGZILLA_ADMIN_KEY** from a clean env.

**Comment by kaihendry** [comment]
After talking with @nbiton who seems to use your scripts to upgrade.

My personal working style is to start from scratch, i.e. rely on https://github.com/unee-t/bugzilla-customisation/blob/master/sql/demo.sql.gz & `make clean`

If I can get a clean env going quicker, i.e. without going the *BUGZILLA_ADMIN_KEY* dance, I would be happy.

**Comment by franck-boullier** [comment]
@kaihendry can you give me the API key that you want me to setup for the admin user? It needs to be consistent with the API key configured in the MEFE/Mongo DB and I don't know where to find that

**Comment by franck-boullier** [comment]
@kai the file to use to create the BZ DB environment with demo user and latest version of the DB schema is [available there in the PR](https://github.com/unee-t/bz-database/pull/71/files#diff-4d57d8ab133840b4d298a47ae6522d71).

I still need to API key you want me to setup for local environments so I can include that in this file.

**Comment by kaihendry** [comment]
Just set a random string as the default demo.sql.gz Administrator key like `SyP7ihXYGXQ68Wd2zJlu6pnId3dhynXN7mOe9HGn` or `forlocaldevtestingonly` if it can take that.

The PR is pretty opaque. The diff is useless.

**Comment by kaihendry** [comment]
Fixed by https://raw.githubusercontent.com/unee-t/bz-database/master/db%20snapshots/unee-t_BZDb_clean_with_demo_users_and_unit_current.sql ? You can close the bug.

**Comment by kaihendry** [comment]
Actually I am not sure **BUGZILLA_ADMIN_KEY** gets used now, in light of user creation being done via uneet/apienroll direct into the database...

So this exercise may have been a waste oft time?

**Comment by franck-boullier** [comment]
> Actually I am not sure BUGZILLA_ADMIN_KEY gets used

We need this when we create a unit or do things that are above a user privilege.

**Comment by kaihendry** [comment]
But when we create a unit, isn't the idea to use https://github.com/unee-t/unit ? i.e. write directly into the DB?

**Comment by franck-boullier** [comment]
This was an example (albeit an incorrect one arguably)
Another (more accurate) example: you need this key so you can create BZ uses via the native BZ API

**Comment by kaihendry** [comment]
Is that what Meteor/Frontend does?

TBH I am just looking for a way of testing **BUGZILLA_ADMIN_KEY=forlocaldevtestingonly** setting in .env in Frontend works.

**Comment by kaihendry** [comment]
This is working. Tested by creating a new user from MEFE.
