### ISSUE TITLE
DB Instance bugzilla contains MyISAM tables that have not been migrated to InnoDB

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#8]
https://ap-southeast-1.console.aws.amazon.com/rds/home?region=ap-southeast-1#dbinstance:id=bugzilla

```
~/lmb/bz-database$ grep -ri MyISAM .
./db snapshots/unee-t_BZFE_v2.13_clean.sql:) ENGINE=MyISAM DEFAULT CHARSET=utf8;
./db snapshots/unee-t_BZFE_v2.11_clean.sql:) ENGINE=MyISAM DEFAULT CHARSET=utf8;
./db snapshots/unee-t_BZFE_v2.12_clean.sql:) ENGINE=MyISAM DEFAULT CHARSET=utf8;
./db snapshots/unee-t_BZFE_v2.8_clean.sql:) ENGINE=MyISAM DEFAULT CHARSET=utf8;
./db snapshots/unee-t_BZFE_v2.10_clean.sql:) ENGINE=MyISAM DEFAULT CHARSET=utf8;
./db snapshots/unee-t_BZFE_v2.9_clean.sql:) ENGINE=MyISAM DEFAULT CHARSET=utf8;
./db snapshots/unee-t_BZFE_v2.7_clean.sql:) ENGINE=MyISAM DEFAULT CHARSET=utf8;
./db snapshots/unee-t_BZFE_v2.7_incl_demo_users.sql:) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

Can these be converted to InnoDB? 

https://github.com/unee-t/bugzilla-customisation/tree/master/sql seems fine. But the dev RDS is what AWS is complaining about.

**Comment by franck-boullier** [comment]
"Can these be converted to InnoDB?"

Not too sure about that... I need to read some documentation and we probably need to do a few tests to make sure that this does not create any issue...

If memory serves, the only table that is still MyISAM is the 'bugs_fulltext' table.

This table is used for the BZ search functionality to search a specific term in either the description or a comment in a bug/case

Not sure why it's not InnoDB but there might be some good reason for that...

**Comment by kaihendry** [comment]
Could you refer to the demo.sql.gz change so it's easier to see what the actual change/work was done. Getting a little bewildered moving between tickets.

**Comment by franck-boullier** [comment]
OK makes sense, will do once we have a stable version for demo.sql.gz that will work with Aurora and the triggers

**Comment by franck-boullier** [comment]
The  table 'bugs_fulltext' has been migrated to InnoDB in DEV/Staging, Demo and PROD
