### ISSUE TITLE
Test users should not have @mailinator.com addresses

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bz-database#87]
Btw local development and demo I think is dependent on the SQL database being primed.
https://github.com/unee-t/bugzilla-customisation/blob/master/Makefile#L23

Mailinator.com seems dead, so the users in our db with @mailinator.com should probably be changed, so emails (e.g. testing notifications) can be looked up.

user+{leonel,marley}@case.dev.unee-t.com I think would be good. This could go on one SNS topic that we could all subscribe to. And the SNS could be uses as a Web hook et al.

The SES receive rule and SNS topics is already setup in the dev account:

<img src="https://s.natalian.org/2018-10-05/1538709987_2558x1406.png">

**Comment by franck-boullier** [comment]
BZ seed script now uses email addresses @case.dev.unee-t.com instead of @mailinator.com
