### ISSUE TITLE
Faciliate recovery and reduce the risk that table `user_group_map` is emptied accidentally

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bz-database#88]
# The problem

We need to improve the procedure that updates the user permissions and group membership in case something like https://github.com/unee-t/bugzilla-customisation/issues/73 happens again.

**Comment by kaihendry** [comment]
I think you figured out that you were truncating the table? https://github.com/unee-t/invite/blob/master/sql/invite_user_in_a_role_in_a_unit.sql#L566

Also you should probably use Transactions so it always roll back to a good state.

**Comment by kaihendry** [comment]
It happened again and unfortunately the instance where it happened on had not rebooted so the binlog_format MIXED parameter hadn't taken affect. :man_facepalming: 

Ref: Case ID 5463168141 in the dev account.

**Comment by franck-boullier** [comment]
Analysis of the PROD database: we have records in the user_group_map table that should not exist:
users are linked to a group_id = 0. This is impossible in theory as the group 0 does not exist...

This might be one of the reason why there is an issue with the existing script.

We need to understand how these records have been created...

**Comment by franck-boullier** [comment]
Updated procedures are now implemented in the DEV/Staging and DEMO environment.
This is database schema v3.25.
We will wait for more tests in the Demo by Uilicious before implementing the change in the PROD

**Comment by franck-boullier** [comment]
PR #89 has been merged into the master.
